version: "3.7"
services:
    app:
        container_name: webapp
        env_file: .env
        restart: always
        build: .
        ports:
            - "8080:8080"
        networks:
            - nodeapp-network
        depends_on:
            - mongo
        volumes:
            - ./webapp:/opt/webapp
    mongo:
        container_name: mongo
        image: mongo:latest
        ports:
            - "27017:27017"
        networks:
            - nodeapp-network
        volumes:
            - ./mongo-volume:/opt/db

networks:
    nodeapp-network:
        driver: bridge
